apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: go-task-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: go-task-orchestrator/auth-service:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: PORT
              value: "8081"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: go-task-orchestrator-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: go-task-orchestrator
spec:
  selector:
    app: auth-service
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP

